### ISSUE TITLE
Testing Problem 1

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project5#2]
As a team tester, I want to create functional components to enhance user interaction and enable seamless navigation within the application. These components should provide access to user profiles, photos, and comments. Additionally, I want to update the TopBar component to display relevant app context based on the content being viewed, so that users can easily explore and interact with the application while maintaining a clear understanding of the context.

By fulfilling this task, we aim to validate the functionality and user experience improvements introduced in this user story, ensuring that our application successfully provides enhanced navigation and context-awareness for our users, so that they can use the application more efficiently and with a clear understanding of the context.

**Comment by JChilds1012** [comment]
Code has been tested.

**Comment by aalqah13** [comment]
Thank you for the feedback.
