### ISSUE TITLE
Testing Problem 2

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project5#5]
As a team tester, I want to verify the implementation of a mechanism for fetching model data from the web server. This is essential to replace the current model data loaded as JavaScript into the DOM, creating a more authentic and functional web application, so that users can interact with real data and experience a more realistic application.

Acceptance Criteria:

    1. Conduct testing to confirm the creation of the FetchModel function for fetching model data from the web server.
    2. Verify that FetchModel can successfully manage multiple requests for data without issues.
    3. Test and validate the modification of components to use the FetchModel for data retrieval, ensuring the elimination of window.models access.
    4. Confirm that the web server's version number is displayed in the TopBar component when visiting the app.

By fulfilling these testing criteria, we aim to validate the replacement of fake model data with real data fetched from the web server. This verification ensures the application's authenticity and functionality for users, providing them with an experience based on real data and enhancing the realism of the application.

**Comment by JChilds1012** [comment]
Problem 2 has been tested.

**Comment by aalqah13** [comment]
Thank you for the feedback.
