### ISSUE TITLE
Code Review Problem 2

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project5#6]
As a Code Reviewer, I want to conduct a code review for the implementation of a mechanism that fetches model data from the web server. This implementation is essential to replace the current model data loaded as JavaScript into the DOM, enhancing the authenticity and functionality of our web application, so that users can interact with real data and have a more realistic experience.

**Comment by 1melkey33** [comment]
Code has been tested and reviewed

**Comment by aalqah13** [comment]
Thank you for the feedback.
